### ISSUE TITLE
Remove threading from entanglement forging

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#208]
Passing Qiskit Runtime components into distributed functions via Python threading modules has caused the `ckt.circuit_cutting.execute_experiments` function to hang intermittently.

This was addressed in #207  by calling `Sampler.run` for each batch of subexperiments before collecting the results by calling the blocking function, `result`, instead of handling the threading ourselves.

Resolution of this issue should include removal of python threading from the entanglement forging modules. This can likely be done in a similar way as #207 . It would be nice to accept Samplers as input directly. Maybe it makes sense to do that refactor as part of resolution of this issue, or maybe it should be addressed in a separate issue

**Comment by garrison** [comment]
I suspect (but have not confirmed) that the real problem -- or at least, something that is more likely to trigger a problem -- is when the code attempts to use the _same_ sampler from multiple threads.  This would explain why the `how_to_generate_exact_sampling_coefficients.ipynb` notebook was failing so often prior to #207: it's because it passes only one sampler to `samplers`, and then the code tries to use that sampler from multiple threads simultaneously.
