### ISSUE TITLE
Support SamplerV2

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#488]
The circuit cutting post-processing uses the `SamplerResult` objects output from `SamplerV1` directly; however, `SamplerV2` will return `PrimitiveResult` objects, so our post-processing should support both types of outputs from the two different sampler interfaces

https://github.com/Qiskit/qiskit/blob/61181ce0681129f9a1d5af43122484f8b6da1bbc/qiskit/primitives/base/base_sampler.py#L231

**Comment by garrison** [comment]
nb: The relevant function is `reconstruct_expectation_values` in https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/main/circuit_knitting/cutting/cutting_reconstruction.py.

**Comment by garrison** [comment]
Tracking issue from Qiskit Aer to support primitives V2: https://github.com/Qiskit/qiskit-aer/issues/2078

**Comment by garrison** [comment]
Actually (reversing course a second time), it seems like we do indeed need to wait for Aer to support SamplerV2 if we are to provide automated tests of this feature, because Qiskit's implemention throws an error: `"StatevectorSampler cannot handle mid-circuit measurements`".  Unless, of course, we want to provide our own `BaseSamplerV2` implementation based on our `simulation.py` -- but I think we are better off waiting on Aer.

**Comment by garrison** [comment]
An alternative would be to use `BackendSamplerV2` together with `AerSimulator`, as suggested at https://github.com/Qiskit/qiskit-aer/issues/2078.  But this would mean waiting for Qiskit 1.1 (which is when `BackendSamplerV2` will first appear in a release) and will also require a fix to https://github.com/Qiskit/qiskit/issues/12043.
